# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    Makefile                                         .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: acharras <marvin@le-101.fr>                +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2019/07/20 10:25:40 by acharras     #+#   ##    ##    #+#        #
#    Updated: 2019/07/24 23:12:27 by acharras    ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #

SRC		= ft_lilfct.c ft_error.c ft_generator.c main.c ft_resolve.c ft_realoc.c

NAME	= bsq

GCC		= gcc 

GCCFLAG	= -Wall -Wextra -Werror

all:	
	$(GCC) $(GCCFLAG) -o $(NAME) ${SRC}

fclean:
	rm $(NAME)
